---

cluster.name: elasticsearch-cluster
network.host: 0.0.0.0

node.master: true
node.data: true
node.ingest: true

discovery.type: single-node
cluster.routing.allocation.disk.threshold_enabled: false