---

filebeat.prospectors:
- type: log
  paths:
    - /var/log/example/*.log
  encoding: plain
  scan_frequency: 10s
  close_inactive: 24h
  ignore_older: 48h

output.logstash:
  hosts: ["logstash:5044"]

  worker: 2
  compression_level: 3
